Fix int overflow in printTableAddCell() (#16495)
When user try to select a big number of rows via PSQL, they may encounter the following error:
ERROR: "Cannot add cell to table content: total cell count of XXX exceeded".
The root cause is the overflow of int type in printTableAddCell(), this commit fixes it.

And it has already been fixed it in 7x and postgres:
- https://github.com/greenplum-db/gpdb/pull/16388
- https://github.com/postgres/postgres/commit/24ea53dcfab7fe463c0cf56095e9fe5d23cdb748