On MAC WEXITSTATUS fails with cannot take the address of an rvalue of type int
On MAC, implementation of WEXITSTATUS uses the address-of operator (unary &)
on its argument, effectively requiring that its argument have storage. Currently,
it being called with the return value of a function, which doesn't have
storage, so the compiler complains.

To workaround the problem, assign the return value of pclose() to a
variable before using WEXITSTATUS
```
utilities/upgrade-helpers.c:177:27: error: cannot take the address of an rvalue of type 'int'
        pg_upgrade_exit_status = WEXITSTATUS(pclose(output_file));
                                 ^           ~~~~~~~~~~~~~~~~~~~
/usr/include/sys/wait.h:144:27: note: expanded from macro 'WEXITSTATUS'
                          ^      ~
/usr/include/sys/wait.h:131:34: note: expanded from macro '_W_INT'
                                 ^ ~
1 error generated.
make: *** [utilities/upgrade-helpers.o] Error 1
```