Fix error code overwrite in cdbdisp_dumpDispatchResult. (#9323) (#9340)
The error code should not set twice with different codes in `errfinish_and_return`.
Since the order of function's parameters is dependent on the compiler.
If the final error code is ERRCODE_INTERNAL_ERROR, file name and line number print out.
```
ERROR:  Error on receive from SEG IP:PORT pid=PID: *** (cdbdispatchresult.c:487)
```

It's strange to print out the file name and line number here.
So, remove ERRCODE_INTERNAL_ERROR, and only keep ERRCODE_GP_INTERCONNECTION_ERROR,
which is also the error code before commit: 143bb7c.

Reviewed-by: Paul Guo <paulguo@gmail.com>
(cherry picked from commit 55d6415bb3d0ada27c85eb138807fd2f5322367b)