Retire gp_reject_internal_tcp_connection
Cherry-picked from 0715a53bb46 with minor conflicts resolved. Original
commit message follows:

We take a number of steps in cdbconn_doConnectStart() to force QD ->
entry DB QE communication to be over Unix Domain Sockets. It is more
performant over TCP/IP, since it is on the same host. Also, since
4b3360292e4c332933faa554ad2d606f37d82cb7, these connections are
considered as authenticated, bypassing the usual pg_hba authentication
procedure (see internal_client_authentication()).

However, if PGHOST/PGHOSTADDR are set in the postmaster environment,
TCP/IP connections are still used instead of Unix Domain Sockets. It is
actually hard to enforce UDSes here as conninfo_add_defaults() would
sprinkle in the value from the environment, if present. Setting the
value of PGHOST to the socket dir (/tmp by default) is also hard, as the
unix_socket_directories GUC is plural, and we would need to actually
read the postmaster.pid file. Too much trouble and not performant.

Till now, the gp_reject_internal_tcp_connection GUC, on by default,
would force authentication of these internal QD -> entry DB TCP/IP
connections via regular HBA, possibly leading to issues such as:

postgres=> select * from foo, pg_sleep(0);
ERROR:  failed to acquire resources on one or more segments
DETAIL:  fe_sendauth: no password supplied

In this case, the current user is one for which password based
authentication has been set up in
$COORDINATOR_DATA_DIRECTORY/pg_hba.conf

To be more friendly to these situations, mark this GUC as defunct. So,
if any TCP/IP connections are created for QD -> entry DB QE, they will
be considered authenticated by default, and bypass HBA.

Reviewed-by: Huansong Fu <fuhuansong@gmail.com>