Avoid re-executing if all tuples of the plan have been emitted. (#9596)
On postgres, holdable cursor will rerun the executor after rewinding to put all
tuples in tuplestore during commit for later access, but for gpdb we do not
support backwards scanning so we just continue executing without rewinding the
executor, this could lead to some issues since some executor nodes are not
written or designed for the case that previously the plan has emitted all tuples.

Typical issues are seen as below:

1. assert failure (in execMotionSortedReceiver())
FailedAssertion("!(!((heap)->bh_size == 0) && heap->bh_has_heap_property)", File: "binaryheap.c"

2. elog(ERROR) like below.
ERROR:  cannot execute squelched plan node of type: 232 (execProcnode.c:887)

Cherry-picked from 3d11e871daefab7cde733d3f985be08d9a9fa8e7

Note there is a small difference int the test against gpdb master.  Need to
disable gp_enable_motion_mk_sort for one test so that we could run into the
affected code path.

Reviewed-by: Hubert Zhang <hzhang@pivotal.io>