Fix possible gprecoverseg stuck
PR #9540 introduces `Incremental recovery/rebalance in parallel`, it
uses WorkerPool to start worker threads. But if error occured inside
run_pg_rewind()'s for loop, cleanup() would be called and all running
workers in the pool would be requested to halt. Unluckily, non-blocking
gpsubprocess.communicate2 would return but leave its returncode None:

> The None value indicates that the process hasn't terminated yet.

After this, inside Worker::run(), logger.debug(self.cmd) would throw
an exception:

> TypeError: %d format: a number is required, not NoneType

Then, logger.debug(self.cmd) again inside its catch, so `addFinishedWorkItem`
would be skipped. Consequently, pool.join() would wait forever in the main
thread.

It is just one use case, WorkerPool may also be used elsewhere.

Fix it by using %s instead of %d to print rc.

(cherry picked from commit 41f0100622a4e51e45dc1ae80e3f1f559aecb72d)