Fix bug of very long UTF-8 encoded query string truncation  [6X] (#16674)
This pr cherry-picks #11946 and #16669 into 6X_STABLE.

Long query log will be truncated when writing log.csv. 
UTF-8 is a variable-length encoding of 1~4 bytes, 
so UTF-8 characters may be truncated in the middle.

Without code change, the test case will meet encoding ERROR:
```
ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0xa3 0x22
```
because the long query log is truncated, 
please refer to the special char in the log.csv `�` as below:
```
床前明月光疑是地上霜举头望明月低头思故乡
独坐幽篁里弹琴复长啸深林人不知明月来相照
千山鸟�",,,,,"PL/Python function "
```

Co-authored-by: t1mursadykov <sti@arenadata.io>
Co-authored-by: Yongtao Huang <yongtaoh@vmware.com>