master: fix gpfdist crash (#13750) (#13761)
Long log:
When we write compressed data into a full disk, gpfdist will return 500 error.
After 5 mins, the session will be removed.
Then, if we write data into the full disk again, gpfdist will fail, like:
```
gz_file_write_one_chunk: Assertion `ret1 != (-2)' failed.
```
This is a phenomenon that users do not expect.
In fact, gpfdist can still work for other request.
We think we shouldn't carry on assert(ret1 != Z_STREAM_ERROR);
If the error happens, we need to judge and return directly, avoiding gpfdist fails.
The log is shown as below:
```
2022-06-27 18:10:55 6837 INFO active segids in session: 0 1 2
2022-06-27 18:10:55 6837 WARN [1:6:1:11] handle_post_request, write error: cannot write into file
2022-06-27 18:10:55 6837 WARN [1:6:1:11] HTTP ERROR: 127.0.0.1 - 500 cannot write into file
2022-06-27 18:10:55 6837 WARN [1:6:1:11] gpfdist read unexpected data after shutdown
// .....................
2022-06-27 18:16:49 6837 INFO remove sessions
2022-06-27 18:16:49 6837 INFO remove out-dated session 812-0000000037.25.0.0:/home/gpadmin/core_analysis/load_files/test_file/demo_str.txt.gz
2022-06-27 18:16:49 6837 INFO free session 812-0000000037.25.0.0:/home/gpadmin/core_analysis/load_files/test_file/demo_str.txt.gz
gpfdist: gfile.c:376: gz_file_write_one_chunk: Assertion `ret1 != (-2)' failed.
```

The commit does not contain a test case, if you want to verify the issue, please following the manual-test-method below:

**1.	create a table "demo_str" and a writable external table "demo_str_ext"**
```
testdb=# \d demo_str
  Table "public.demo_str"
 Column | Type | Modifiers
--------+------+-----------
 c      | text |
Distributed by: (c)

testdb=# \d demo_str_ext
External table "public.demo_str_ext"
 Column | Type | Modifiers
--------+------+-----------
 c      | text |
Type: writable
Encoding: UTF8
Format type: text
Format options: delimiter '|' null '\N' escape '\'
External options: {}
External location: gpfdist://127.0.0.1:8083/demo_str.txt.gz
Execute on: all segments
Distributed by: (c)
```
These tow tables have the same structure. Please prepare enough data in table "demo_str" for test.

**2. 	create a  space-limited folder**
Please follow the instruciton in https://developpaper.com/how-to-limit-the-size-of-a-single-folder-in-linux-system/
In my environment，the folder "/home/gpadmin/core_analysis/load_files/test_file" can only contain 10M data.

**3.	start gpfdist server**
```
$ gpfdist -v -d /home/gpadmin/core_analysis/load_files/test_file -p 8083 -l /home/gpadmin/core_analysis/load_files/gpfdist.log
2022-07-05 10:45:07 19987 INFO Before opening listening sockets - following listening sockets are available:
2022-07-05 10:45:07 19987 INFO IPV6 socket: [::]:8083
2022-07-05 10:45:07 19987 INFO IPV4 socket: 0.0.0.0:8083
2022-07-05 10:45:07 19987 INFO Trying to open listening socket:
2022-07-05 10:45:07 19987 INFO IPV6 socket: [::]:8083
2022-07-05 10:45:07 19987 INFO Opening listening socket succeeded
2022-07-05 10:45:07 19987 INFO Trying to open listening socket:
2022-07-05 10:45:07 19987 INFO IPV4 socket: 0.0.0.0:8083
2022-07-05 10:45:07 19987 INFO Opening listening socket succeeded
Serving HTTP on port 8083, directory /home/gpadmin/core_analysis/load_files/test_file

```

**4. send compressed data into space-limited folder**
The folder path is “/home/gpadmin/core_analysis/load_files/test_file”, we will receive 500 error due to full disk.
```
testdb=# insert into demo_str_ext select * from demo_str;
ERROR:  http response code 500 from gpfdist (gpfdist://127.0.0.1:8083/demo_str.txt.gz): HTTP/1.0 200 ok  (seg2 127.0.0.1:15436 pid=24402)
```

**5.	wait totally 5 minutes**
Please refer to function sessions_cleanup() in gpfdist.c. After 300 seconds (5 mintutes), the useless sessions will be removed automatically.
```C
	for (i = 0; hi && i < numses; i++, hi = apr_hash_next(hi))
	{
		apr_hash_this(hi, 0, 0, &entry);
		s = (session_t*) entry;

		if (s->nrequest == 0 && (s->mtime < apr_time_now() - 300
				* APR_USEC_PER_SEC))
		{
			session[n++] = s;
		}
	}
```
**6.	if we send compressed data to the full disk again, we will receive 500 error again, no longer core dump.**
```
testdb=# insert into demo_str_ext select * from demo_str;
ERROR:  http response code 500 from gpfdist (gpfdist://127.0.0.1:8083/demo_str.txt.gz): HTTP/1.0 200 ok  (seg1 127.0.0.1:15435 pid=24401)

```
After revision, the reported crash will not happen again.

Signed-off-by: Yongtao Huang<yongtaoh@vmware.com>