Fix assert when inserting/updating table with trigger and returning ctid.
- How to reproduce

1. create table and trigger

```
gpadmin=# create table loc1 (f1 serial, f2 text);
gpadmin=# CREATE FUNCTION trig_row_before_insupdate() RETURNS TRIGGER AS $$
  BEGIN
    NEW.f2 := NEW.f2 || ' triggered !';
    RETURN NEW;
  END
$$ language plpgsql;
gpadmin=# CREATE TRIGGER trig_local_before BEFORE INSERT OR UPDATE ON loc1
FOR EACH ROW EXECUTE PROCEDURE trig_row_before_insupdate();
```

2. insert a value, then assert pops

```
gpadmin=# INSERT INTO loc1(f2) VALUES ('test') RETURNING ctid;
ERROR:  Unexpected internal error (execTuples.c:1559)  (seg1 slice2 10.117.190.45:7001 pid=19255) (execTuples.c:1559)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(htup->t_self)) != ((void *)0)) && ((&(htup->t_self))->ip_posid != 0))))", File: "execTuples.c", Line: 1559)
HINT:  Process 19255 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
```
- root cause

the root cause is that if a table has trigger, the slot will be modified by trigger and be different from parentslot in `ExecInsert()`
and then the ExecProcessReturning() will crash due to invalid parentslot.

so we fix this issue referring to the fdw handling in `ExecInsert()`

Co-authored-by: Amy Bai <ajie@vmware.com>