be-gssapi-common.h: Introduce configure guard
c2e56adb5b46e0c95aa7a1970d92cacca4cf0548 introduced kerberos delegation
in libpq. It missed the ENABLE_GSS guard rail in be-gssapi-common.h.
Without this patch, even if we are building without the --with-gssapi
flag, we would run into the following error (reported on Ubuntu 20.04.4
LTS) if we don't have dependencies installed:

../../../src/include/libpq/be-gssapi-common.h:20:10: fatal error: gssapi/gssapi.h: No such file or directory
   20 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.