Allow squelching on the coordinator to handle SIGPIPE of ExternalScan (#14212)
Executing a query that doesn't fetch all tuples from the external scan that execute
program on coordinator leads to the next error:

ERROR:  external table table_master command ended with SHELL TERMINATED by
signal SIGPIPE (13)
DETAIL:  Command: execute:(echo foo; sleep 1; echo bar)

There are several cases when gpdb ends an unfinished plan: extended protocol,
cursors. Greenplum communicates with shell command by pipe, it closes the pipe while
shell command steel sends results. And SIGPIPE happens here. In such cases,
if an external web table is executed on segments, then it uses squelching
mechanics, that provides a separate way to handle unfinished yet plan nodes and
simply ignore SIGPIPE of ExternalScan. But the squelching doesn't execute
for master-only plans on the coordinator. So the solution is allowing squelching
on the master for such plans.