[6X] Fixing gpcheckperf error when ran with -f and -V option (#15192)
* Calling gpssh in non-verbose mode when fetching hostname

 gpcheckperf utility can be run in verbose mode in 2 ways :
 "-v" and "-V" which is verbose mode and very verbose mode respectively.
 When gpcheckperf ran in very verbose mode (-V) option, it runs gpssh
 command with -v option which results in the extra lines of output.
 Those extra lines were leading to run-time exception:
   "ValueError: too many values to unpack"

 gpssh command when ran in regular mode output is as follows:

 $ gpssh -h sdw2 hostname
    [sdw2] sdw2

When ran gpssh in verbose mode, output is as follows:

$gpssh -v -h sdw2 hostname
  [WARN] Reference default values as $MASTER_DATA_DIRECTORY/gpssh.conf could not be found
  Using delaybeforesend 0.05 and prompt_validation_timeout 1.0

  [Reset ...]
  [INFO] login sdw2
  [sdw2] sdw2
  [INFO] completed successfully

  [Cleanup...]

With this changes, made sure that gpssh takes verbose flag and calls command accordingly.
When calling hostname command, gpssh() is called in non-verbose flag.
Added test cases to test various scenarios in verbose and extra verbose mode.

* gpcheckperf: fixing value error exception on single host

When matrix test ran with single hostn and, value error exception was printed.
E.g.
 $gpcheckperf -h cdw  -r M -d /data/gpdata/ --duration=3m -V
  Traceback (most recent call last):
  File "/usr/local/greenplum-db-devel/bin/gpcheckperf", line 1005, in <module>
    main()
  File "/usr/local/greenplum-db-devel/bin/gpcheckperf", line 975, in main
    netResult, seglist = runNetPerfTestMatrix()
  TypeError: cannot unpack non-iterable NoneType object

Function runNetPerfTestMatrix was returning single value when no results to print.
With this commit fixing value error and added test-case to verify the same.